name: "⚙️ jobs"

on:
  push:
    branches:
      - main
    paths:
      - "back/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws
    defaults:
      run:
        working-directory: ./back

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: sa-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Build
        run: make build

      - name: Terraform init
        run: terraform -chdir=infra init

      - name: Plan Terraform changes
        run: terraform -chdir=infra plan -out=tfplan

      - name: Apply Terraform Changes
        run: terraform -chdir=infra apply -auto-approve
        env:
          TF_VAR_sender_email: ${{ secrets.SENDER_EMAIL }}
          TF_VAR_s3_bucket_name: ${{ secrets.S3_BUCKET_NAME }}
          TF_VAR_dynamodb_table_name: ${{ secrets.DYNAMODB_TABLE_NAME }}
